### ISSUE TITLE
安装没有报错，使用main.py的时候报错了

### ISSUE THREAD

**Issue by wzc2019** [YaoFANGUK/video-subtitle-generator#10]
conda 和 pip 安装的步骤都没有报错。
以下是在win11系统下，运行main的信息报错信息。
```python
return program
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

SystemError: <built-in method __contains__ of dict object at 0x00000162E8958BC0> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\main.py", line 228, in <module>
    sg.run()
  File ".\main.py", line 199, in run
    transcript = recognizer(data)
  File ".\main.py", line 35, in __call__
    _, probs = self.model.detect_language(mel)
  File "D:\Miniconda3\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\video-subtitle-generator-main\video-subtitle-generator-main\backend\whisper\decoding.py", line 56, in detect_language
    language_probs = [
  File "C:\Users\Administrator\Downloads\video-subtitle-generator-main\video-subtitle-generator-main\backend\whisper\decoding.py", line 59, in <listcomp>
    for j, c in zip(tokenizer.all_language_tokens, tokenizer.all_language_codes)
  File "C:\Users\Administrator\Downloads\video-subtitle-generator-main\video-subtitle-generator-main\backend\whisper\tokenizer.py", line 228, in all_language_codes
    return tuple(self.decode([l]).strip("<|>") for l in self.all_language_tokens)
  File "C:\Users\Administrator\Downloads\video-subtitle-generator-main\video-subtitle-generator-main\backend\whisper\tokenizer.py", line 228, in <genexpr>
    return tuple(self.decode([l]).strip("<|>") for l in self.all_language_tokens)
  File "C:\Users\Administrator\Downloads\video-subtitle-generator-main\video-subtitle-generator-main\backend\whisper\tokenizer.py", line 141, in decode
    return self.tokenizer.decode(token_ids, **kwargs)
  File "D:\Miniconda3\lib\site-packages\transformers\tokenization_utils_base.py", line 3474, in decode
    token_ids = to_py_obj(token_ids)
  File "D:\Miniconda3\lib\site-packages\transformers\utils\generic.py", line 174, in to_py_obj
    return [to_py_obj(o) for o in obj]
  File "D:\Miniconda3\lib\site-packages\transformers\utils\generic.py", line 174, in <listcomp>
    return [to_py_obj(o) for o in obj]
  File "D:\Miniconda3\lib\site-packages\transformers\utils\generic.py", line 175, in to_py_obj
    elif is_tf_tensor(obj):
  File "D:\Miniconda3\lib\site-packages\transformers\utils\generic.py", line 151, in is_tf_tensor
    return False if not is_tf_available() else _is_tensorflow(x)
  File "D:\Miniconda3\lib\site-packages\transformers\utils\generic.py", line 142, in _is_tensorflow
    import tensorflow as tf
  File "D:\Miniconda3\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "D:\Miniconda3\lib\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "D:\Miniconda3\lib\site-packages\tensorflow\python\eager\context.py", line 33, in <module>
    from tensorflow.python.client import pywrap_tf_session
  File "D:\Miniconda3\lib\site-packages\tensorflow\python\client\pywrap_tf_session.py", line 19, in <module>
    from tensorflow.python.client._pywrap_tf_session import *
ImportError: initialization failed
```

**Comment by YaoFANGUK** [comment]
卸载numpy重新装一下：
> pip uninstall numpy

> pip install numpy
