### ISSUE TITLE
安装没有报错，运行python main.py时出现问题

### ISSUE THREAD

**Issue by Roots-Ban** [YaoFANGUK/video-subtitle-generator#12]
(vsgEnv) E:\video-subtitle-generator\backend>python main.py
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    import librosa
  File "D:\Python\Miniconda3\envs\vsgEnv\lib\site-packages\librosa\__init__.py", line 209, in <module>
    from . import core
  File "D:\Python\Miniconda3\envs\vsgEnv\lib\site-packages\librosa\core\__init__.py", line 6, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "D:\Python\Miniconda3\envs\vsgEnv\lib\site-packages\librosa\core\audio.py", line 11, in <module>
    import scipy.signal
  File "D:\Python\Miniconda3\envs\vsgEnv\lib\site-packages\scipy\signal\__init__.py", line 331, in <module>
    from ._peak_finding import *
  File "D:\Python\Miniconda3\envs\vsgEnv\lib\site-packages\scipy\signal\_peak_finding.py", line 8, in <module>
    from scipy.stats import scoreatpercentile
  File "D:\Python\Miniconda3\envs\vsgEnv\lib\site-packages\scipy\stats\__init__.py", line 468, in <module>
    from ._rvs_sampling import rvs_ratio_uniforms, NumericalInverseHermite  # noqa
  File "D:\Python\Miniconda3\envs\vsgEnv\lib\site-packages\scipy\stats\_rvs_sampling.py", line 3, in <module>
    from ._unuran import unuran_wrapper
  File "unuran_wrapper.pyx", line 221, in init scipy.stats._unuran.unuran_wrapper
  File "unuran_wrapper.pyx", line 200, in scipy.stats._unuran.unuran_wrapper._setup_unuran
  File "messagestream.pyx", line 36, in scipy._lib.messagestream.MessageStream.__cinit__
OSError: Failed to open file b'C:\\Users\\\xe5\x8f\xbc\xe7\x9d\x80\xe9\x9b\xb6~1\\AppData\\Local\\Temp\\scipy-_60rnr8b'

**Comment by YuanyangZhang** [comment]
我的也是这样，请问解决了嘛？

**Comment by Roots-Ban** [comment]
> 
系统用户文件路径中存在中文，你换个系统非中文的。系统用户名，文件名没法更改，我换了个电脑测试的
