### ISSUE TITLE
安装依赖报错

### ISSUE THREAD

**Issue by dev-coco** [YaoFANGUK/video-subtitle-generator#15]
运行 `python gui.py` 的时候出现下面的错误

```Python
ModuleNotFoundError: No module named 'utils.formatter'
```

已经尝试过 `pip install utils` 安装 `utils` 可是还是出现错误。

Python 版本 3.8.12

**Comment by wongchichong** [comment]
在video-subtitle-generator 里面

cd video-subtitle-generator 后
用powershell 
$env:PYTHONPATH += ";$pwd/backend"

或其他 弄好 PYTHONPATH

**Comment by YaoFANGUK** [comment]
修复了 再试下

**Comment by dev-coco** [comment]
运行 gui.py 成功，可以显示界面，但是运行的过程中出现缺少模块，后来我安装了 whisper、PySimpleGUI、config 之后就正常了，但是选择视频后点击「运行」出现下面的错误。
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/xxxxxx/opt/miniconda3/envs/vsgEnv/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/xxxxxx/opt/miniconda3/envs/vsgEnv/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "gui.py", line 173, in task
    from backend import main
  File "/Users/xxxxxx/Downloads/video-subtitle-generator-main/backend/main.py", line 89, in <module>
    class SubtitleGenerator:
  File "/Users/xxxxxx/Downloads/video-subtitle-generator-main/backend/main.py", line 200, in SubtitleGenerator
    concurrency=config.DEFAULT_CONCURRENCY,
AttributeError: module 'config' has no attribute 'DEFAULT_CONCURRENCY'
```

**Comment by YaoFANGUK** [comment]
你直接pip install -r requirements.txt 不行吗

**Comment by wongchichong** [comment]
我补了这个 在 requirements.txt 下面...试试看

...
ffmpeg-python==0.2.0
zhconv==1.4.3
PySimpleGUI==4.60.4
config==0.5.1
openai-whisper

**Comment by YaoFANGUK** [comment]
requirements.txt 原本就有这些吧

**Comment by dev-coco** [comment]
> 我补了这个 在 requirements.txt 下面...试试看
> 
> ... ffmpeg-python==0.2.0 zhconv==1.4.3 PySimpleGUI==4.60.4 config==0.5.1 openai-whisper

解决了
