### ISSUE TITLE
SystemError: initialization of _internal failed without raising an exception

### ISSUE THREAD

**Issue by SequoiaDu** [YaoFANGUK/video-subtitle-generator#22]
GPU: Tesla P4
pyTorch: 2.0.1 (CUDA 11.8).

I first set up a new conda environment following the instructions, but the model was running on the CPU.

I then installed pyTorch CUDA using the command generated on the [official website](https://pytorch.org/get-started/locally/). Now running vsg throws the following error.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\USERNAME\.conda\envs\vsgEnv\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\USERNAME\.conda\envs\vsgEnv\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "gui.py", line 173, in task
    from backend import main
  File "D:\Program Files\Video Subtitle Generator\backend\main.py", line 15, in <module>
    import librosa
  File "C:\Users\USERNAME\.conda\envs\vsgEnv\lib\site-packages\librosa\__init__.py", line 209, in <module>
    from . import core
  File "C:\Users\USERNAME\.conda\envs\vsgEnv\lib\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "C:\Users\USERNAME\.conda\envs\vsgEnv\lib\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "C:\Users\USERNAME\.conda\envs\vsgEnv\lib\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Users\USERNAME\.conda\envs\vsgEnv\lib\site-packages\librosa\util\__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\Users\USERNAME\.conda\envs\vsgEnv\lib\site-packages\librosa\util\utils.py", line 9, in <module>
    import numba
  File "C:\Users\USERNAME\.conda\envs\vsgEnv\lib\site-packages\numba\__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "C:\Users\USERNAME\.conda\envs\vsgEnv\lib\site-packages\numba\np\ufunc\__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "C:\Users\USERNAME\.conda\envs\vsgEnv\lib\site-packages\numba\np\ufunc\decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
```

Is there any specific pyTorch version/configuration I should use? Thanks!

**Comment by YaoFANGUK** [comment]
you can just try 
```
pip install -r requirements.txt
```

**Comment by NingerJohn** [comment]
@SequoiaDu 你好，你的问题解决了吗？
