### ISSUE TITLE
No module named 'fsplit'`

### ISSUE THREAD

**Issue by dawnyoake** [YaoFANGUK/video-subtitle-generator#23]
创建虚拟环境后，均按照readme进行，在环境下运行GUI.PY之后出现报错。
Logs如下：

`成功打开文件：F:/video2txt/02/002.mp4
['F:/video2txt/02/002.mp4']
Exception in thread Thread-1:
Traceback (most recent call last):
  File "F:\Miniconda\envs\vsgEnv_1\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "F:\Miniconda\envs\vsgEnv_1\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File ".\gui.py", line 173, in task
    from backend import main
  File "F:\video2txt\VSG\video-subtitle-generator\backend\main.py", line 23, in <module>
    from backend import config
  File "F:\video2txt\VSG\video-subtitle-generator\backend\config.py", line 10, in <module>
    from fsplit.filesplit import Filesplit
ModuleNotFoundError: No module named 'fsplit'`

尝试了自动/手动单独装fsplit，但是装不上，因为fsplit包里缺少info库

(vsgEnv_1) (vsgEnv_1) PS F:\video2txt\VSG\video-subtitle-generator> python "E:\Download of Chrome\dist\fsplit-1.0.0\setup.py"
Traceback (most recent call last):
  File "E:\Download of Chrome\dist\fsplit-1.0.0\setup.py", line 11, in <module>
    from fsplit import __version__
  File "E:\Download of Chrome\dist\fsplit-1.0.0\fsplit\__init__.py", line 11, in <module>
    from info import __version__ # define __version__ variable
ModuleNotFoundError: No module named 'info'

是我哪里做错了吗？

**Comment by dawnyoake** [comment]
(vsgEnv) PS D:\video-subtitle-generator> python .\backend\main.py
请输入文件完整路径：D:\video-subtitle-generator\002.mp4
运行程序
Traceback (most recent call last):
  File ".\backend\main.py", line 275, in <module>
    sg.run()
  File ".\backend\main.py", line 214, in run
    recognizer = AudioRecogniser(language=self.language)
  File ".\backend\main.py", line 32, in __init__
    self.model = whisper.load_model(self.model_path)
  File "D:\video-subtitle-generator\backend\whisper\__init__.py", line 144, in load_model
    checkpoint = torch.load(fp, map_location=device)
  File "C:\Users\Lilac\miniconda3\envs\vsgEnv\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\Lilac\miniconda3\envs\vsgEnv\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'f'.

**Comment by superherowcw** [comment]
ModuleNotFoundError: No module named 'fsplit'，有解决的嘛？

**Comment by YaoFANGUK** [comment]
pip install filesplit==3.0.2

**Comment by Fanstering** [comment]
换成filesplit怎么调用呢？报错还是一样的
