### ISSUE TITLE
目前代码的large模型无法正常调用

### ISSUE THREAD

**Issue by iceunlim** [YaoFANGUK/video-subtitle-generator#33]
环境是win10 ltsc  python3.8.
以下是报错信息:
`Traceback (most recent call last):
    sg.run()
  File "backend/main.py", line 214, in run
    recognizer = AudioRecogniser(language=self.language)
  File "backend/main.py", line 32, in __init__
    self.model = whisper.load_model(self.model_path)
  File "D:\Projects\video-subtitle-generator\backend\whisper\__init__.py", line 147, in load_model
    dims = ModelDimensions(**checkpoint["dims"])
KeyError: 'dims'`
medium模型可以正常生成字幕文件.

**Comment by YaoFANGUK** [comment]
已经修复
