### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by Djionter** [YaoFANGUK/video-subtitle-generator#4]
按照说明，运行程序，执行python backend/main.py，会提示No module named 'fsplit'

然后自己单独pip install fsplit安装fsplit，仍然会提示

  Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Fisher\AppData\Local\Temp\pip-install-5zl3_dr0\fsplit_45d13962e7b147008eee4fa18d381872\setup.py", line 11, in <module>
          from fsplit import __version__
        File "C:\Users\Fisher\AppData\Local\Temp\pip-install-5zl3_dr0\fsplit_45d13962e7b147008eee4fa18d381872\fsplit\__init__.py", line 11, in <module>
          from info import __version__ # define __version__ variable
      ModuleNotFoundError: No module named 'info'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

请问如何解决

**Comment by YaoFANGUK** [comment]
不是fsplit，是filesplit==3.0.2

**Comment by Djionter** [comment]
是在requirement.txt里面加上filesplit==3.0.2吗

**Comment by YaoFANGUK** [comment]
是
